---
- name: Get Health
  hosts: all
  gather_facts: no
  tasks:
    - name: Run show health command
      ale.aos8.aos8_command:
        commands: show health
      register: health_output

    - name: Extract CPU and Memory Usage
      set_fact:
        cpu_usage: "{{ health_output.stdout[0] | regex_search('CPU\\s+(\\d+)', '\\1') | first }}"
        memory_usage: "{{ health_output.stdout[0] | regex_search('Memory\\s+(\\d+)', '\\1') | first }}"

    - name: Display CPU and Memory Usage
      debug:
        msg: "Current CPU Usage: {{ cpu_usage }}%, Current Memory Usage: {{ memory_usage }}%"
