---
- name: Get Health
  hosts: all
  gather_facts: no
  tasks:
    - name: Run show health command
      ale.aos8.aos8_command:
        commands: show health
      register: health_output

    - name: Extract CPU and Memory Usage
      set_fact:
        cpu_usage: "{{ health_output.stdout[0] | regex_search('CPU\\s+(\\d+)', '\\1') | first }}"
        memory_usage: "{{ health_output.stdout[0] | regex_search('Memory\\s+(\\d+)', '\\1') | first }}"

    - name: Display CPU Usage in green if below or equal 45%
      debug:
        msg: "Current CPU Usage: {{ cpu_usage }}%"
      when: cpu_usage | int <= 45

    - name: Display CPU Usage in red if above 45%
      debug:
        msg: "\033[91mCurrent CPU Usage: {{ cpu_usage }}%\033[0m"
      when: cpu_usage | int > 45

    - name: Display Memory Usage in green if below or equal 45%
      debug:
        msg: "Current Memory Usage: {{ memory_usage }}"
      when: memory_usage | int <= 45

    - name: Display Memory Usage in red if above 45%
      debug:
        msg: "\033[91mCurrent Memory Usage: {{ memory_usage }}%\033[0m"
      when: memory_usage | int > 45
